Dataset ini
vmkononenko/music-dsp pull request #8
Opened 2021-03-08 15:49 UTC by Misipuk

2021-03-09 19:25 UTC, vmkononenko requested changes

2021-03-09 19:25 UTC, vmkononenko commented on tools/DatasetExtraction/dataset.py
> +    #returns songlist with Chord class instances
I don't think so. IMO `load()` should return a list of lists or a map of lists, with the first layer representing a song, and a second list of segments representing sequence of chord with their start and end timestamps.

2021-03-09 19:25 UTC, vmkononenko commented on tools/DatasetExtraction/dataset.py
> +        pass
there should be public methods actually

2021-03-09 19:25 UTC, vmkononenko commented on tools/DatasetExtraction/dataset.py
> +                    #will also chech cq_max
this is not what we need from this validation, really. And it should be abstract. For now forget about it and just create an abstract stub.

2021-03-09 19:25 UTC, vmkononenko commented on tools/DatasetExtraction/dataset.py
> +    def get_hmm_matrix_i(self):
this is the best method to start implementation from. Let's implement it's logic stubbing everything else. Once we have this method you can start working on the rest of stuff.

2021-03-10 18:41 UTC, Misipuk commented
Parsing, Ini matrix

2021-03-10 18:42 UTC, closed without merging